### ISSUE TITLE
Заменить decko на core-decorators

### ISSUE THREAD

**Issue by clicktronix** [fullstack-development/react-redux-starter-kit#113]
У core-decorators намного больше декораторов и он поддерживает tree-shaking.
@Znack @in19farkt @chmnkh @NikitaRzm Что думаете?

**Comment by in19farkt** [comment]
Надо код посмотреть, если там всё хорошо, то думаю нужно брать))

**Comment by NikitaRzm** [comment]
Огонь, меняем )

Сорцы ок вроде )
