### ISSUE TITLE
Выпилить @types/_helpers

### ISSUE THREAD

**Issue by sk1e** [fullstack-development/react-redux-starter-kit#132]
Есть куда более полное, хорошо поддерживаемое собрание утилит https://github.com/pirix-gh/ts-toolbelt. Предлагаю отказаться от своих и использовать это решение

**Comment by in19farkt** [comment]
Поддерживаю. ts-toolbelt вообще пушка, давненько уже юзаю

**Comment by kinda-neat** [comment]
Поддерживаю, + наших всех подтолкнет к более углубленному изучению typescript

**Comment by chmnkh** [comment]
Там вообще нифига не для всего решение  есть. Примеры типов, которые не заменяются тулбелтом: `GetProps`, `CheckIdentity`. Причем первый вообще дофига где используется, поэтому так себе задача.

**Comment by in19farkt** [comment]
`CheckIdentity<T, R>` вроде есть, причем скорее всего даже лучше, наш `CheckIdentity<T, R>` какого-то возвращает тип T, а по хорошему должен вернуть true или false

**Comment by sk1e** [comment]
>  `GetProps`

`React.ComponentProps`
