### ISSUE TITLE
Выпилить shared/helpers/decorators

### ISSUE THREAD

**Issue by sk1e** [fullstack-development/react-redux-starter-kit#137]
там находится только memoizeByProps. Это можно делать через createSelector из reselect, API которого все знают и понимают. Этот хелпер дублирует функции, захламляя кодовую базу

**Comment by safr** [comment]
декораторы в тс дерпикейтид уже. Декораторы @bind и так далее вообще не актуальны, можно юзать стрелочные функции в методах классов для биндинга.
