### ISSUE TITLE
Выпилить shared/helpers[replaceObjectKeys, replaceObjectValues]

### ISSUE THREAD

**Issue by sk1e** [fullstack-development/react-redux-starter-kit#139]
Легко заменяются на R.mapObjIndexed. Захламляют кодовую базу

**Comment by prodderman** [comment]
Серегей, ты сам то пробовал это выпилить с помощью R.mapObjIndexed? @sk1e

**Comment by sk1e** [comment]
> Серегей, ты сам то пробовал это выпилить с помощью R.mapObjIndexed? @sk1e

я так понял replaceObjectKeys нельзя выпилить этим, да? Думаю нужно вот [это](https://char0n.github.io/ramda-adjunct/2.21.0/RA.html#.renameKeys) использовать тогда

**Comment by in19farkt** [comment]
А оно сейчас где-то используется в демке? Если нет, то смело выпииваем, не нужно ни на что заменять.

**Comment by prodderman** [comment]
все эти хэлперы используются

**Comment by prodderman** [comment]
> я так понял replaceObjectKeys нельзя выпилить этим, да? Думаю нужно вот это использовать тогда  

да это подойдет, но ради этого либу тянуть?

**Comment by sk1e** [comment]
> да это подойдет, но ради этого либу тянуть?

что тебя смущает?

**Comment by chmnkh** [comment]
> > да это подойдет, но ради этого либу тянуть?
> 
> что тебя смущает?

не знаю, что Степана смущает, но меня смущает, что мы держим в зависимостях библиотеку ради одной функции из нее

ну и что, что тришейкнется, держать целую зависимость в пэкэйдж джейсоне, когда можно просто 1 файл на 5 строк написать - это какой-то прикол вообще, я даже не понимаю, че мы тут спорим

**Comment by sk1e** [comment]
> > > да это подойдет, но ради этого либу тянуть?
> > 
> > 
> > что тебя смущает?
> 
> не знаю, что Степана смущает, но меня смущает, что мы держим в зависимостях библиотеку ради одной функции из нее
> 
> ну и что, что тришейкнется, держать целую зависимость в пэкэйдж джейсоне, когда можно просто 1 файл на 5 строк написать - это какой-то прикол вообще, я даже не понимаю, че мы тут спорим

Ты во-первых пишешь - тратишь время; во-вторых держишь модулем, заставляя всех запоминать что именно такая вот херня у нас есть в хелперах и если что используйте её, противопоставляя цельной методологии - все общие алгоритмы брать из ramda/ramda-adjunct. В третьих какая разница сколько ты берёшь из этой библиотеки? Когда тебе понадобится вторая функция из этой библиотеки, что ты будешь делать? В четвёртых ты так говоришь как будто эту зависимость в package.json ты держишь собственными руками и это довольно тяжёло. Ну лежит она там,  в чём проблема конкретно? npm'у тяжелее работать будет?

**Comment by in19farkt** [comment]
если к рамде прилагается какая-то крутая библиотека значительно расширяющая возможности рамды, то я за то чтобы добавить ее в зависимости, как минимум ради того, чтобы остальная команда тоже была в курсе. Я вот не был в курсе и до сих пор, если рамды не достаточно, пишу свой хелпер.

**Comment by chmnkh** [comment]
короче ок, я на самом деле не могу рационально объяснить, почему мне не нравится, поэтому давайте воткну
