### ISSUE TITLE
Выпилить shared/helpers/react/withComponent

### ISSUE THREAD

**Issue by sk1e** [fullstack-development/react-redux-starter-kit#141]
Покажите use сases этого хелпера пожалуйста. API выглядит неочевидным, уверен что есть либо лучшие альтернативы, либо место этому в каком-нибудь локальном месте на конкретном проекте, вместо каталога который содержит полезные вещи для типичного проекта

**Comment by in19farkt** [comment]
Это хелпер для MUI, нужен чтобы привязать к MUI компоненте пропс component и смержить пропсы MUI компонента и компонента переданного в component, его можно смело выпиливать, т.к. MUI сейчас поддерживает мерж пропсов из коробки.
