### ISSUE TITLE
Выпилить shared/helpers/react/withProps

### ISSUE THREAD

**Issue by sk1e** [fullstack-development/react-redux-starter-kit#142]
Решение на каких-нибудь замыканиях будет лучше этого, я считаю. Без зависимостей от внешнего модуля, без дополнительного компонента в дереве, которых и так немало. Ещё непонятно как называть компоненты которые этот хелпер возвращает. Или приведите примеры, пожалуйста, если я ошибаюсь

**Comment by in19farkt** [comment]
Нужен в очень редких специфичных кейсах, думаю можно выпиливать
