### ISSUE TITLE
Переименовать каталог с action creators из actions в actionCreators

### ISSUE THREAD

**Issue by sk1e** [fullstack-development/react-redux-starter-kit#149]
Имя должно отражать суть, а сейчас не отражает

**Comment by in19farkt** [comment]
вообще не понятно где что нужно переименовать ))
дай ссылку чтоли

**Comment by chmnkh** [comment]
> Имя должно отражать суть, а сейчас не отражает

двачую

> вообще не понятно где что нужно переименовать ))

у нас файлы с экшн креэйторами называются actions, хотя должны назваться actionCreators, потому что там не экшны, а экшн креэйторы)

**Comment by in19farkt** [comment]
ааа) ну ок))
