### ISSUE TITLE
Пофиксить SSR

### ISSUE THREAD

**Issue by Znack** [fullstack-development/react-redux-starter-kit#171]
1. Запустить проект в dev-режиме, проверить, что фронтенд отдаётся браузеру уже отрендеренной страницей без всяких ошибок
1. Запустить проект в prod-режиме, проверить, что фронтенд отдаётся браузеру уже отрендеренной страницей без всяких ошибок

Все появившиеся ошибки надо исправить, сделать запуск SSR стабильным.

Потом можно пообщаться с @in19farkt по поводу след таски о SSR: https://github.com/fullstack-development/react-redux-starter-kit/issues/158

**Comment by Geksanit** [comment]
Сервер не рендерит верстку потому что асинхронная фича вложена в фичу(т.е. компонента, обернутая в withAsyncFeatures). Это ещё предстоит исправить.
например RepositoriesSearchLayoutComponent на сервере подтягивает данные, а внутри есть Layout, соотвественно для него данных нет и рендерится null.

**Comment by Znack** [comment]
А в итоге ишью можно закрывать, или тут еще остались косяки? @Geksanit @in19farkt

**Comment by in19farkt** [comment]
Ну оно вроде бы работает, но отдает пустую страницу из-за асинхронных фич, если убрать асинхронные фичи, то должно работать

**Comment by Znack** [comment]
А то есть сама проблема отгрузки асинхронных фич не решена? А у нас там фичи в демо проекте есть асинхронные? Может их все синхронными пока сделать?

**Comment by in19farkt** [comment]
да, проблема осталась, там на сколько я помню подгружаются и отрисовываются только фичи находящиеся на верхнем уровне дерева, если мы вложим асинхронные фичи друг в друга, то та что будет глубже заблокирует рендер. Я думаю тему с асинхронными фичами нужно как-то комплексно решать (если мы хотим наш стартеркит развивать), а сейчас стоит всё сделать синхронным, т.к. текущее решение не адаптировано в полной мере под SSR

**Comment by Znack** [comment]
Окей, я тогда это ишью пока закрываю, а про перевод асинхронных страниц отдельно таску сделаю.
