### ISSUE TITLE
Create mvp versions for projects

### ISSUE THREAD

**Issue by clicktronix** [fullstack-development/react-redux-starter-kit#43]
- [x] remove all unnecessary

- [x] add wrappers over basic MUI elements (inputs, buttons, selectors, icons, etc.)

- [x] connect the redux-form and set up basic fields (inputs, selectors, checkboxes, radio)

- [x] connect favicon (works in both normal and isomorphic mode)

- [x] configure the i18n service

- [x] set up a theme

- [x] set up routing

- [x] add demo with base components and i18n

**Comment by NikitaRzm** [comment]
Еще починить scss для работы с миксинами, инклюдами и пр., сейчас в последней версии ругается стайллинт на эти темы)

**Comment by clicktronix** [comment]
@NikitaRzm Никит, можешь примеры кинуть с косячным поведением линтера? чтоб я поправил

**Comment by NikitaRzm** [comment]
![image](https://user-images.githubusercontent.com/16317879/51159064-c5ea6500-18b9-11e9-9348-e70f97aa6d63.png)


То, с чем я столкнулся: миксины, ифы и инклуды не завелись.
Там же вебпак выдает проблему с группировкой похожих инструкций, это вот посмотри на include группе.

Ну и погоняй остальные ключевые слова типа @extend там и т.п. вещей.
