### ISSUE TITLE
Create jss cascade styles intro

### ISSUE THREAD

**Issue by clicktronix** [fullstack-development/react-redux-starter-kit#49]
- расписать общие принципы написания стилей в jss

- как писать и использовать модификаторы или как писать стили от пропсов (хелпер styledBy)

- как и где использовать compose

- испольлзование вложенных селекторов

- best practice компании по использованию jss

**Comment by in19farkt** [comment]
Было бы круто оформить примеры конкретных кейсов в кодсандбоксе, чтобы можно было зайти, посмотреть код, возможно что-то продебажить. Чтобы это выглядело примерно так https://github.com/final-form/react-final-form#examples
