### ISSUE TITLE
 Проработка переводов

### ISSUE THREAD

**Issue by NikitaRzm** [fullstack-development/react-redux-starter-kit#63]
Я изучил i18next. Удовлетворяет всем архитектурным предпочтениям и предлагает большой в перспективе функционал (типа locize для удаленного перевода).

Что нужно:
- подцепить и настроить само ядро i18n (есть в экзампла react-i18next);
- выдать апи для использования в сагах;
- выдать апи для использования во вьюхе (react-i18next);
- описать тестовый бекенд (пусть будет пока локальным файлом) для хранения переводов (https://www.i18next.com/how-to/add-or-load-translations)
- показать корректную работу смены языка (где-то должна быть кнопочка на демостраницах в хедере например)
- ассайнить на меня мерж )

**Comment by in19farkt** [comment]
@NikitaRzm нас это устраивает?
https://bundlephobia.com/result?p=i18next@13.1.4 - 10.2kB gzip
https://bundlephobia.com/result?p=react-i18next@9.0.4 - 7kB gzip

**Comment by NikitaRzm** [comment]
Да, приемлемый трейдофф )
i18n достаточно важная штука (при том опциональная).
И предлагает достаточно возможностей для того, что нужно. Я думаю, что наша поделка (которую надо поддерживать еще ио бновлять сопутственно) обойдется дороже просто. Так-что можно пожертвовать. Ну не забыть сделать отключаемым это.

**Comment by clicktronix** [comment]
@in19farkt У них там таска с переходом на хуки висит, думаю будет поменьше чутка весить потом. Хотя бы react-18next

**Comment by clicktronix** [comment]
Я на выходных смогу заняться этим
