### ISSUE TITLE
Обновить английскую документацию

### ISSUE THREAD

**Issue by chmnkh** [fullstack-development/react-redux-starter-kit#77]
Есть некоторые наработки по английской доке по архитектуре. Чтобы они не пропадали, апдейтну всю английскую доку.

**Comment by NikitaRzm** [comment]
А редми есть в планах перевести?)

**Comment by chmnkh** [comment]
По идее то можно, но он какой-то вообще сейчас странный. Часть про снапшоты, например, вообще не понять зачем нужна, потому что оф документация с головой покрывает то, что у нас написано.

**Comment by in19farkt** [comment]
Да, там некоторые вещи можно выпилить, про тесты это по сути выдержки из оф документации, чтобы под рукой было.

**Comment by chmnkh** [comment]
Если доберемся таки до ридми, то надо будет нев таск делать, эту закрою
