### ISSUE TITLE
текстовый инпут languages  в настройках

### ISSUE THREAD

**Issue by dasmike** [fullstack-development/react-redux-starter-kit#94]
в модалке с настройками поиска инпут languages текстовый. непонятно в каком формате вбивать язык. эт к тому же никак не валидируется. похорошему его надо сделать селектом

**Comment by chmnkh** [comment]
крч, гитхаб не дает апи какого-либо, чтобы языки получить все, я предлагаю распарсить [файл с языками](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) из [Linguist](https://github.com/github/linguist), который гитхаб [юзает](https://help.github.com/en/articles/about-repository-languages) для определения языков реп, и положить файл с языками в assets какие-нибудь внутри фичи, и селект потом бахнуть из языков полученных, нормальное решение?

либо так либо руками вводить, но там опять же никак особо не провалидируешь и формат не укажешь, потому что сам гитхаб апи этого не уточняет вообще

**Comment by Znack** [comment]
Ну или десяток языков самим накидать самых популярных, а остальные просто через инпут ручками позволить вбивать. Чтобы автокомплит был с необязательным выбором из списка

**Comment by Znack** [comment]
Хотя это сломает голову чувакам

**Comment by Znack** [comment]
Можно пресеты как у птички:

![image](https://user-images.githubusercontent.com/2928964/55228975-3b759880-524e-11e9-9df2-688f798fc0b1.png)

**Comment by chmnkh** [comment]
че за пресеты в чем отличие от селекта?

**Comment by Znack** [comment]
А ты точно увидел скриншот и посмотрел на https://ptichka.moscow? :)

это не совсем автокомплит, ты все равно руками вбиваешь значение, просто можешь щелкнуть видные сразу фиксированные значения (которых всего 3-5 штук обычно для примера самых популярных)

**Comment by chmnkh** [comment]
мне кажется это не то что нам надо)
селект в принципе норм, но вот эта проблема с языками стоит
причем писать навскидку несколько языков это имхо какая-то фигня

**Comment by NikitaRzm** [comment]
@chmnkh просьба - когда пишешь или думаешь что это "фигня", сразу это обосновывать, чтоб было ясно сразу, в какую сторону думать отвечающему)

**Comment by Znack** [comment]
Селект — сложнее для популярных выборов, у нас никто не будет всерьез пользоваться этой формой и от пресетов кайфанут, чтобы самим не вводить ничего :)

А кому надо, тот текстом любой остальной язык вобьет, главное, что мы примером показали в пресетах что можно просто текстом вбивать :)

**Comment by chmnkh** [comment]
> @chmnkh просьба - когда пишешь или думаешь что это "фигня", сразу это обосновывать, чтоб было ясно сразу, в какую сторону думать отвечающему)


> Хотя это сломает голову чувакам

я из этого сделал вывод, что Серега сам к этому пришел уже, поэтому ничего не стал пояснять

для меня это фигня - потому что это выглядит как какая-то халтура или недопиленная фича
и по факту это так и есть

**Comment by in19farkt** [comment]
Моё имхо. Селект в данном случае херня, нет апишки которая отдаст все языки, а хардкодить какой-то список тоже не варант, т.к. он со временем должен изменяться, постоянно появляются новые языки.

Мне кажется тут пресеты норм впишутся, берем 5-10 самых популярных языков, и под инпутом делаем списком кнопки с логотипами, как на птичке, нажимаешь логотип, инпут заполняется. Нужен другой язык, впиши руками.

**Comment by chmnkh** [comment]
ну популярные языки точно так же поменяться могут в общем-то)

**Comment by in19farkt** [comment]
> ну популярные языки точно так же поменяться могут в общем-то)

это да, но это не так критично, как отсутствие интересуемого языка в селекторе.

**Comment by chmnkh** [comment]
ну вообще говоря можно же и руками ввести
но идея с пресетами мне в принципе нравится, го пресеты
