### ISSUE TITLE
Список реп (дизайн)

### ISSUE THREAD

**Issue by NikitaRzm** [fullstack-development/react-redux-starter-kit#99]
![image](https://user-images.githubusercontent.com/16317879/55229604-14b86180-5250-11e9-9034-8cbaccfac9b7.png)

Насколько уместно будет тут карточки зафигарить наподобие материаловских? Сейчас у меня немного смешивается информация, можно у Юли спросить еще на предмет этого и на предмет line-height в тексте )

**Comment by NikitaRzm** [comment]
Ссылки тоже надо бы подчеркивать при наведении - как нативное поведение ) и для :visited стили прописать)

**Comment by in19farkt** [comment]
Для ссылок у MUI есть компонента Link. Поддерживаю идею с карточками
